apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signaling-server
  template:
    metadata:
      labels:
        app: signaling-server
    spec:
      containers:
      - name: signaling-server
        image: daosgava/signaling-server:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000