apiVersion: v1
kind: Service
metadata:
  name: signaling-server-service
spec:
  type: LoadBalancer
  selector:
    app: signaling-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000